### ISSUE TITLE
Scroll is not reset after page change

### ISSUE THREAD

**Issue by azhry** [palembang-digital/website#38]
Ketika scroll ke tengah di home dan kemudian klik menu Team, halamannya masih tetap scroll ke tengah tidak mengulang lagi dari atas

**Comment by azhry** [comment]
#43 when i check it again, this bug is already fixed. i'm not sure if it's 100% fixed, or only worked on my computer

**Comment by ariefrahmansyah** [comment]
You're right, the bug when changing from Home to Team page is solved. But not from the another way which is from Team page to Acara, Tentang, or Kontak.
